### ISSUE TITLE
Load geojson feature collection

### ISSUE THREAD

**Issue by mskzo** [geoman-io/maplibre-geoman#6]
Hi, 

I'm testing your maplibre version. I want to know how to load a feature collection on map in order to edit it. 
I tried some not documented methods and also tried to load directly on "gm-source" using the setData but is not working.

Best Regards

**Comment by mscno** [comment]
Hi @mskzo 

Thanks for the report. 
I added documentation on how to add existing geojson data to the map.
We dont support directly adding a geojson FeatureCollection yet (we will soon), so you will need to add every element individually in a loop.

See docs here: https://geoman.io/docs/maplibre/importing-data

**Comment by mskzo** [comment]
Thanks @mscno for the quick response.

During my recent testing, I loaded nearly 14,000 features into the editor. While it loads successfully, I’ve noticed that some features disappear when I begin editing, and the performance becomes very laggy.

I encountered a similar issue with the Leaflet version, where it struggled to handle large datasets effectively. I’m wondering if this is something that is being addressed in your roadmap, as it’s a significant concern for working with large-scale data.

In my experience with Leaflet version, I solved this problem by using geojson-vt (with canvas) and enabling each feature in Geoman by click (and activating selected editing function on it). This approach allows the handling of very large datasets without performance issues. I’m planning to replicate this method (without canvas) on the maplibre version, and if you're interested, I’d be happy to share my implementation.

**Comment by zxwild** [comment]
@mskzo, MapLibre can display, move, and zoom in/out a very large count of features; they use `geojson-vt` internally to display shapes. However, each update rebuilds all features, which affects performance.

History:
- Initially, we created a source + layers for each feature - it was amazingly slow, even for 50 features.
- Then, a single GeoJSON source was added with a few layers for visible representation. In this case, feature display is OK, but updates aren't.
- Then we added a "main" source to display features and a "temporary" source to display target feature updates - this is the current state, and it works well enough to handle up to 8,000 features, I believe.

When you `mousedown` on a feature, it moves from the "main" to the "temporary" source and back on a `mouseup`.

The issue on MapLibre for reference:
https://github.com/maplibre/maplibre-gl-js/issues/4364

> I'm wondering if this is something that is being addressed in your roadmap.

Yes, it's possible to apply some tricks, and we'll definitely try to do so. I think the most promising way for the beginning is "click-to-edit", as in your case, which will reduce marker count since they are currently displayed for all available shapes.

Further ideas are welcome!

**Comment by mskzo** [comment]
Thank you for your detailed response.

I made some tests using a GeoJSON source with 100k features, including three layers (point, line, shape) and achieved excellent performance by applying a simple trick that adds features to the Geoman "control" on click.

![demo](https://github.com/user-attachments/assets/b4968db6-34fe-45fc-9c77-84bec29f7ff0)

However, during testing, I noticed that some important information seems to be missing from the documentation. Could you please share the methods for the following: Retrieving the current GeoJSON data, Clearing the data, Setting default styles

Additionally, I found that the toolbar and the generic configuration (GmOptionsPartial) are not documented. Any guidance you can provide on these would be greatly appreciated.

**Comment by zxwild** [comment]
> Could you please share the methods for the following: Retrieving the current GeoJSON data, Clearing the data, Setting default styles

API is not as stable as we would like it to be. But here are some clues:
In the latest commits there are methods: `gm.features.importGeoJson(geoJson)`, `gm.features.exportGeoJson()`.

Also each GeoJSON feature has a wrapper class `FeatureData`, this class has methods like: `featureData.getGeoJson()`, `featureData.updateGeoJsonGeometry(geometry)`.

You can iterate over all features by: `gm.features.forEach()`.
A feature can be removed by: `gm.features.delete(featureData)`.

Styles could be set in `gmOptions.layerStyles.polygon.regular = <maplibre.LayerSpecification>`.

There are not so many options in GmOptionsData, basically: controls position, throttling delay, styles, and control buttons availability.

The project is TypeScripted, so you should be able to see possible options.

Actually public API aligning is a task for now..
